name: nex
description: NEX Remote Desktop Client
publish_to: 'none'
version: 0.1.0-alpha.13

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  provider: ^6.1.2

  # Navigation
  go_router: ^14.2.7

  # WebRTC
  flutter_webrtc: ^1.1.0

  # Signaling
  web_socket_channel: ^2.4.0

  # HTTP
  http: ^1.2.2

  # Crypto
  crypto: ^3.0.3
  sodium_libs: ^2.0.0

  # Storage
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0

  # Desktop window management
  window_manager: ^0.4.0

  # Utils
  uuid: ^4.4.2
  permission_handler: ^11.3.1
  url_launcher: ^6.2.5
  logger: ^2.5.0
  file_picker: ^8.1.2
  path_provider: ^2.1.6
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
