-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class com.elstella.flutter_app.** { *; }
-dontwarn io.flutter.**
-dontwarn io.flutter.plugins.**
-dontwarn com.elstella.flutter_app.**
